import type { Metadata } from "next";
<<<<<<< HEAD
import { Plus_Jakarta_Sans } from "next/font/google";
=======
import localFont from "next/font/local";
>>>>>>> d6d423b235ba48f3c5c379337685ad0f75e8d452
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

<<<<<<< HEAD
const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
=======
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
>>>>>>> d6d423b235ba48f3c5c379337685ad0f75e8d452
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${plusJakarta.variable} ${plusJakarta.variable} antialiased`}
      >
        {children}
      </body>
=======
      <SessionProvider refetchInterval={120} session={session}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </SessionProvider>
>>>>>>> d6d423b235ba48f3c5c379337685ad0f75e8d452
    </html>
  );
}
